# SPEEDS
FORWARD_SPEED = 5.0
SLIGHT_SPEED = 2.8
MAX_SPEED = 6.28

# WALL FOLLOWING
DESIRED_RIGHT = 70

# THRESHOLDS
WALL_DIFF = 5
FRONT_AVOID_ON = 75
WALL_THRESHOLD = 75
RIGHT_OPEN_THRESHOLD = 45

# GOAL SETTINGS
GOAL_CONFIRM_TIME = 5
GOAL_TOUCH_THRESHOLD = 130

# RECOVERY
STUCK_TIME_LIMIT = 30
RECOVERY_STEPS = 15

# Smoothing factor (0 = no change, 1 = instant change)
SMOOTHING_ALPHA = 0.35
MAX_ACCEL = 0.2