# Speeds
FORWARD_SPEED = 5.5
TURN_SPEED = 3.0
SLIGHT_SPEED_DIFF = 1.5

# Behaviour timing
ESCAPE_LIMIT = 20
STUCK_LIMIT = 50
STATE_CONFIRM_COUNT = 3

# Avoid (hysteresis)
FRONT_AVOID_ON = 80
FRONT_AVOID_OFF = 70

# Wall following sensitivity
WALL_DIFF_SMALL = 6
WALL_DIFF_STRONG = 12
WALL_DEADZONE = 5

# Wall detection threshold
WALL_THRESHOLD = 75